# BACKEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management-backend
  template:
    metadata:
      labels:
        app: student-management-backend
    spec:
      containers:
        - name: backend
          image: roshi12/student-management-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/studentmanagement"

---

# FRONTEND DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management-frontend
  template:
    metadata:
      labels:
        app: student-management-frontend
    spec:
      containers:
        - name: frontend
          image: roshi12/student-management-frontend:latest
          ports:
            - containerPort: 3000
